### ISSUE TITLE
Publish packages for Linux ARM64

### ISSUE THREAD

**Issue by tibdex** [activeviam/jdk4py#73]
This is required to be able to install this package in a Docker image built on macOS with Apple Silicon without having to resort to the `--platform=linux/am64` option slowing the container execution.

See https://pythonspeed.com/articles/docker-build-problems-mac.

Depends on https://github.com/actions/runner-images/issues/5631 since relying on self-hosted runners makes testing and publishing more cumbersome.

**Comment by PeterBartram** [comment]
Hello @tibdex 

I originally posted this on the PR but figured here would be a better place to ask. 
I just came here to report his exact issue. I think it is stopping the java-runtime being downloaded when I install jdk4py into a docker container with ubuntu OS and M1 silicone. I can see that you have made changes already, is this now considered to be complete? What is the expected release schedule for this? I don't mean to rush things but rather figure out if I should wait for the release or do a manual install of the library including your changes.

Thanks!

**Comment by tibdex** [comment]
Hi @PeterBartram, the last release supports Linux Arm64. Were you able to try it and fix your Docker issue?
